# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  ruby: circleci/ruby@2.0.1
  node: circleci/node@4.7.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Rspec
          command: bundle exec rspec
  ember:
    docker:
      - image: cimg/node:16.20.1
    executor: node/default
    steps:
      - checkout
      - run:
          name: Which npm?
          command: npm -v
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - rspec
      - ember
